//! Fenced code block languages recognized by GitHub (Linguist).
//!
//! `linguist_languages.txt` is generated by `scripts/update-linguist.sh`: lowercased names,
//! default aliases (spaces -> '-'), `fs_name`s, `aliases` and extensions without the dot.
//! Linguist's `Language[]` (used for fences) is case-insensitive, so lookups lowercase first.

use std::sync::LazyLock;

static LINGUIST: &str = include_str!("linguist_languages.txt");

/// Identifiers GitHub renders natively (diagrams/maps/math) or that are common and harmless.
const EXTRA: &[&str] = &[
    "mermaid",
    "geojson",
    "topojson",
    "stl",
    "math",
    "d2",
    "text",
    "plaintext",
    "console",
    "shell-session",
    "diff",
];

/// Common non-Linguist ids and the id to use instead.
const MAPPING: &[(&str, &str)] = &[
    ("plain", "text"),
    ("none", "text"),
    ("nohighlight", "text"),
    ("output", "text"),
    ("log", "text"),
    ("psql", "sql"),
    ("katex", "math"),
    ("latex-math", "math"),
];

/// Sorted, deduplicated list of known identifiers.
static KNOWN: LazyLock<Vec<&'static str>> = LazyLock::new(|| {
    let mut v: Vec<&str> = LINGUIST
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .chain(EXTRA.iter().copied())
        .collect();
    v.sort_unstable();
    v.dedup();
    v
});

/// Whether `lang` is a known identifier (case-insensitive) or in `extra`.
pub fn is_known(lang: &str, extra: &[String]) -> bool {
    let l = lang.to_lowercase();
    KNOWN.binary_search(&l.as_str()).is_ok() || extra.iter().any(|e| e.eq_ignore_ascii_case(lang))
}

/// Up to three replacement suggestions for an unknown `lang`, best first.
pub fn suggest(lang: &str) -> Vec<&'static str> {
    let l = lang.to_lowercase();
    if let Some((_, to)) = MAPPING.iter().find(|(from, _)| *from == l) {
        return vec![to];
    }
    // Ids of three characters or fewer match too much noise at distance 2.
    let max = if l.chars().count() <= 3 { 1 } else { 2 };
    let mut c: Vec<(usize, &str)> = KNOWN
        .iter()
        .map(|k| (distance(&l, k), *k))
        .filter(|(d, _)| *d <= max)
        .collect();
    let n = l.len();
    c.sort_by_key(|&(d, k)| (d, k.len().abs_diff(n), k.len(), k));
    c.into_iter().take(3).map(|(_, k)| k).collect()
}

/// Optimal string alignment distance (Levenshtein plus adjacent transpositions, so `rsut` -> `rust` is 1).
fn distance(a: &str, b: &str) -> usize {
    let (a, b): (Vec<char>, Vec<char>) = (a.chars().collect(), b.chars().collect());
    let w = b.len() + 1;
    let mut d: Vec<usize> = (0..(a.len() + 1) * w)
        .map(|k| {
            if k < w {
                k
            } else if k % w == 0 {
                k / w
            } else {
                0
            }
        })
        .collect();
    for i in 1..=a.len() {
        for j in 1..=b.len() {
            let cost = usize::from(a[i - 1] != b[j - 1]);
            let mut v = (d[(i - 1) * w + j] + 1)
                .min(d[i * w + j - 1] + 1)
                .min(d[(i - 1) * w + j - 1] + cost);
            if i > 1 && j > 1 && a[i - 1] == b[j - 2] && a[i - 2] == b[j - 1] {
                v = v.min(d[(i - 2) * w + j - 2] + 1);
            }
            d[i * w + j] = v;
        }
    }
    d[a.len() * w + b.len()]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn list_is_sane() {
        assert!(KNOWN.len() > 1000);
        assert!(
            KNOWN
                .iter()
                .all(|k| !k.contains(' ') && *k == k.to_lowercase())
        );
        for k in [
            "rust", "rs", "sh", "shell", "console", "mermaid", "d2", "text", "diff", "js", "py",
        ] {
            assert!(is_known(k, &[]), "{k}");
        }
    }

    #[test]
    fn suggestions() {
        assert_eq!(suggest("rsut").first(), Some(&"rust"));
        assert_eq!(suggest("plain"), vec!["text"]);
        assert_eq!(distance("rsut", "rust"), 1);
        assert_eq!(distance("kitten", "sitting"), 3);
    }
}
